version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  node-app:
    build:
      context: ./nodejs
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
